// <auto-generated />
namespace Lcps.Division.Directory.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserMemberSchema001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserMemberSchema001));
        
        string IMigrationMetadata.Id
        {
            get { return "201508111600375_UserMemberSchema001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
